version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "alexa-chatgpt-calendar"
s3_bucket = ""
s3_prefix = "alexa-chatgpt-calendar"
region = "us-east-1"
confirm_changeset = true
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Environment=prod"
]
image_repositories = []